// <auto-generated />
namespace CarServiceCare.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsuranceEnums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsuranceEnums));
        
        string IMigrationMetadata.Id
        {
            get { return "202012050201599_InsuranceEnums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
