// <auto-generated />
namespace CarServiceCare.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CarRemoveCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarRemoveCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101554279_CarRemoveCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
